// Generated by CoffeeScript 1.6.3
(function() {
  this.Accessible = (function() {
    function Accessible() {
      var accessory, _i, _len, _ref;
      _ref = this.attr_accessible;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        accessory = _ref[_i];
        this[accessory] = function() {
          var fn, value,
            _this = this;
          value = void 0;
          fn = function(v) {
            if (v === void 0) {
              return value;
            }
            value = v;
            return _this;
          };
          this[accessory] = fn;
          return this[accessory]();
        };
        this[accessory]();
      }
    }

    return Accessible;

  })();

}).call(this);
